# Generated by Django 3.1.7 on 2021-02-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='creator',
        ),
        migrations.AddField(
            model_name='bug',
            name='assignee',
            field=models.CharField(default='assign a user to fix the bug', max_length=100),
        ),
        migrations.AddField(
            model_name='bug',
            name='name',
            field=models.CharField(default='name of bug', max_length=100),
        ),
        migrations.AddField(
            model_name='bug',
            name='operating_system',
            field=models.CharField(default='computer system', max_length=100),
        ),
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(default='level of priority', max_length=100),
        ),
    ]
