# Generated by Django 3.1.7 on 2021-02-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_auto_20210225_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
